language: python
sudo: false
python:
  - 2.7
script:
  - pip install coveralls
  - python setup.py develop
  - coverage run setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Kaniabi
  on:
    tags: true
    repository: zerotk/terraformer
  password:
    secure: j6Nk8E/uAAmrVfEBDvCNQoPZhkFy7x2+La+6nJp8MhtavQLdSQ1CxezsfkrfS0N6heYri1WOD4UBdJ0+VyP5HcY+zSXi2WFEBZNhyuzpukDrm31B8mYULCjfY+wYU/nOwiogjZ1SCeOFW0oddOMQwFjhIO+z1wLNQRx0vKP9FErKdyCPXOOO/Nhysc7YzdPeWuK+68AZkMlK0hNbyVlZDshcJ8p2hIu2Zh5MHkLv/T///Ea+GYW68sIXlyR5Au4rjGPRalWXKITwBw9asibAXhijji0RafH+dxn6qIbpxpAJZ9aUucL0JGLOyCz2DWI7RzK1b54KwFlvlpbngUGxfJ6GH0AIaboVNQnXCV5mPnZhrRSKHV1qJePbA4XXmtf3XrV434ZzDTUJAQ4vtJhHV/9780m4MYn0FoIYCAyBP7uikn7rmsC/3dWS3D5mUNbPNZmb5g1pUBia/nbLgp7pVbq53PkTqanDBsKxF1T92IsvpPR7rTnfgzfAawzCD6aiHABeMJA0nlPsjyiuC8lJwZGc4YV373pW/9A6uP4wzDP0ypQqaZN8SHPCW74wUtkw4EM6iYKgtlUAvXhsAiDNR38Envh0ilPKA2lf/fwJhxzNdyJs5cwuwOmP06z7at/lI1Qm8QHHl/4ehI3vpLJS7bN+f7gWe96rPucep0tOKwo=
